### ISSUE TITLE
Cannot change Formspree email address

### ISSUE THREAD

**Issue by reaganch** [samesies/barber-jekyll#1]
Firstly, thanks a lot for sharing this jekyll theme. I've been trying to use it to build my own website, and host it on Bitbucket. I have, however, run into a strange error when modifying the site.email variable in the _config.yml file, to define the email address to which all Formspree entries should be sent. If I leave it as okay@samesies.io, the Formspree form submission works just okay. If I change it to any other email address, after I click Send in the contact form, I get a "Something Went Wrong" error message. Would you be able to pinpoint where I may be doing something wrong? I just spent a few hours trying to troubleshoot this, but couldn't solve it. Thanks!

And apologies if I just spammed your email address with test submits while I was trying to troubleshoot this issue. It took me a while to figure out what I was doing before I realised I might be spamming you.

**Comment by reaganch** [comment]
Some reading up seems to indicate that I might need a Formspree Gold account to submit forms using AJAX, which I think your theme uses. Not quite sure what AJAX is, since I'm quite new to web development, but would you have any suggestions on how this might be sidestepped?

**Comment by thomasvaeth** [comment]
So it looks like Formspree has changed AJAX to Gold only. It wasn't like this when I built the theme, so I guess confirmed emails before the switch still work. I will look into another alternative and update the theme when I find one.

**Comment by reaganch** [comment]
Thanks for clarifying. Some searching online led me to http://enformed.io/ which offers free AJAX submissions, at least for now. The free tier is limited to 100 submissions per month, which is probably enough for me at this stage. I changed the submission link at the _includes/formspree.html page to https://www.enformed.io/<token>, and the subject field name from _subject to *subject, and I get emails at my address upon clicking Submit; however, the "Something Went Wrong" message still appears. No idea what else I'd have to change to make this message go away.

**Comment by reaganch** [comment]
Sorry, closed it by mistake.

**Comment by reaganch** [comment]
Just wanted to check if you've had the chance to find any suitable alternatives to Formspree.io. Any advice on what may be causing the issue I've faced using Enformed.io would also be much appreciated. This is the last major issue I need to resolve before publishing my website live.

**Comment by thomasvaeth** [comment]
You can edit `_assets/js/components/_formspree.js` to try to see what's wrong. I included the `package.json` and `gulpfile.js` files to allow editing of the source code. I probably won't get to this for a couple weeks.

**Comment by thomasvaeth** [comment]
Switched to [Formcarry](https://formcarry.com/). Some things changed so you will need to update your theme. You really only need to change ` _includes/formspree.html` to `<form id="form" class="form" action="{{ site.formcarry }}" method="POST">`, get rid of the subject field, and add `formcarry`  to the `_config.yml`.

**Comment by reaganch** [comment]
It works! Thanks!!
