### ISSUE TITLE
Ruby 2.6.0 ffi dependency error

### ISSUE THREAD

**Issue by ChisholmKyle** [samesies/barber-jekyll#10]
ffi version 1.9.25 requires Ruby less than 2.6.0, so an error occurs when Ruby 2.6.0 is installed.
I updated ffi  to version 1.10.0 in `gemfile.lock` to resolve the issue.

**Comment by thomasvaeth** [comment]
Updated Jekyll version, which updated dependencies in the `Gemfile.lock`.
