### ISSUE TITLE
Deprecation warning with Document#tags

### ISSUE THREAD

**Issue by ChisholmKyle** [samesies/barber-jekyll#11]
I get this deprecation warning many times during the build

    Deprecation: Document#tags is now a key in the #data hash.
    Deprecation: Called by ["C:/tools/ruby26/lib/ruby/gems/2.6.0/gems/jekyll-3.6.3/lib/jekyll/document.rb:374:in `method_missing'"].

The watch/build seems to working but theses warnings are really annoying and I don't know how to fix them.

**Comment by thomasvaeth** [comment]
Changed pagination gem from `jekyll-paginate` to `jekyll-paginate-v2`. `v2.1.0` currently doesn't work for pagination on autogenerated pages, so downgraded to `v2.0.0`.
