### ISSUE TITLE
Trying to change favicon

### ISSUE THREAD

**Issue by jnragu** [samesies/barber-jekyll#12]
I'm trying to change the default favicon. I uploaded a new image and replaced the default one inside the assets/images folder with my own and gave the file the same name of "favicon.ico". I then pushed the files to github to deploy my site. 
However, occasionally the old favicon keeps showing up when I load the website. Doen't make sense to me since the old image is no longer in the assets/images folder.

**Comment by thomasvaeth** [comment]
How are you hosting the site? It seems like the favicon is just cached locally for you. What happens when you try through incognito? Or try pressing Command + Shift + R to do a hard refresh.

I'm closing issue because it seems unrelated to the theme.
