### ISSUE TITLE
github pages  not a recognized Liquid tag.

### ISSUE THREAD

**Issue by sunseekers** [samesies/barber-jekyll#16]
Your site is having problems building: The tag tags_list on line 15 in _includes/footer.html is not a recognized Liquid tag. For more information, see https://help.github.com/en/articles/page-build-failed-unknown-tag-error.

![image](https://user-images.githubusercontent.com/25503586/60586257-48150a00-9dc4-11e9-800a-68439d9df8f2.png)

**Comment by thomasvaeth** [comment]
Please read the README.

**Comment by DannyDannyDanny** [comment]
### There is no way to launch a user GitHub page without a 3rd party

I've spent the better part of day trying to befriend git and YAML... **specifically I'm trying to follow this instruction:**

> GitHub Pages does not support custom plugins. The tag list and tag pagination are built using custom plugins. There are several options to avoid any errors while deploying to production.
> * Run `bundle exec jekyll build` ... and manually add the contents of the _site folder to the gh-pages branch.

After spending 2-3 hours neck-deep in StackOverflow git questions, user / organizational Github Pages cannot be setup using the `gh-pages`-branch.

### Could you help me form a guide for setting up via Netlify?

1. `mkdir USER.github.io`
2. `cd USER.github.io`
3. `git clone https://github.com/samesies/barber-jekyll.git .`
4. `bundler install`
5. `bundler exec jekyll serve`
6. `git remote set-url origin https://github.com/USER/USER.github.io.git`
7. `???`

**Comment by thomasvaeth** [comment]
You can sign up with Netlify with your Github account. You can then just link your repo to your account, so Netlify will rebuild whenever you push. It is really easy to set up and they have documentation for all of this.

**Comment by DannyDannyDanny** [comment]
Barely managed to Sign up for Netlify and connect my repository before the whole thing was deployed.

For anyone struggling with deployment: 
* follow the steps in [my previous comment](https://github.com/samesies/barber-jekyll/issues/16#issuecomment-524386638)
* Build the Jekyll page with `bundler install` followed by `bundler exec jekyll serve`
* use your GitHub account to sign up to Netlify
*. when prompted to, choose the repository created earlier: _USER.github.io_

I hope this helps someone 🤷‍♂

**Comment by suryagram** [comment]
Highly recommend this approach. One caveat though:
Don't name your git repo USER.github.io. GitHub has special rules for domains that match that format, and it won't allow you to not have a GitHub pages site for that repo. This becomes annoying b/c your netlify page will link to your github pages page, which will give you the GitHub pages 404 error. 

Just name your repo anything else, and you'll avoid the nightmare that is Github pages.
