### ISSUE TITLE
Ruby Sass has reached end-of-life

### ISSUE THREAD

**Issue by stevenjmesser** [samesies/barber-jekyll#17]
First off, thank you very much for this theme, it's cracking. Well written documentation, too. 

[Ruby Sass has reached end-of-life](http://sass.logdown.com/posts/7828841) and SassC is the recommended replacement. Apparently [the thing to do is wait until Jekyll 4.0.0 comes out](https://github.com/jekyll/jekyll-sass-converter/issues/74) as Jekyll has a dependency on Sass.

Is that right?

**Comment by thomasvaeth** [comment]
All Sass in this theme is compiled through Gulp. I am going to close this for now assuming anyone who is customizing this theme is following the already included process instead of adding more steps the the `_config.yml` to use Jekyll's process.
