### ISSUE TITLE
Changing the header/splash image height for posts/pages

### ISSUE THREAD

**Issue by ochema** [samesies/barber-jekyll#23]
Hey, great theme!

I've been tweaking it for my blog and have been trying for a while to change the maximum height or aspect ratio of the 'splash' image underneath the title of each post (if an image has been selected). I tried changing some values in _post.scss and _posts.scss but that did not do the trick.

In which direction should I be looking for this change?

Quick unrelated question too: I set the site title to an image instead of plain text by changing:

`{{ site.title }}` in /_includes/header.html to `<img style="height:2.5em;" src="/assets/images/header-logo.svg"></img>`

Is that a good method?

**Comment by thomasvaeth** [comment]
Are you compiling the SCSS to CSS after making the change?

**Comment by chaodonghu** [comment]
Like @thomasvaeth said you have to compile the scss to css. 

(1) Start the app with `npm start` or `bundle exec jekyll serve`
(2) Utilize gulp to watch the styles `gulp`

Any changes you make within the `.scss` files will now be minified into `assets/css/app.mins.css` and you can see the changes on localhost
