### ISSUE TITLE
Customizing pages

### ISSUE THREAD

**Issue by umayrh** [samesies/barber-jekyll#27]
First, thanks for an elegant and easy-to-use theme. I've a couple of questions, coming from someone who has little experience with Jekyll and not much front-end. I can learn quickly.

1. I'd like to create a new page that serves as an archive of all posts. Is it possible to do that automatically - as in every time I add a post to `_post`. 

2. How can I manage a page, not just a post, using markdown? Seems like I'd create a new layout that uses the markdown div. Is that correct?

**Comment by thomasvaeth** [comment]
I would suggest reading through the Jekyll documentation.
