### ISSUE TITLE
No content when go live

### ISSUE THREAD

**Issue by li6834300** [samesies/barber-jekyll#39]
Hi, when i hosted on local, the contents were fine, but when I push live, there is no content up there. Is it only happen to me? I didn't see anyone has the same issue...

**Comment by li6834300** [comment]
It just has no posts in the body, the rest of layouts are just fine.

**Comment by thomasvaeth** [comment]
You can't host this on `gh-pages` unless you only add the contents of the `_site` folder to that branch. https://github.com/samesies/barber-jekyll#deployment
