### ISSUE TITLE
ruby_dep version incompatibility

### ISSUE THREAD

**Issue by reaganch** [samesies/barber-jekyll#65]
I'm just cloned your repo on a Linux Mint 21.3 machine and ran `bundle install` but got the following error message:

```
ruby_dep-1.5.0 requires ruby version >= 2.2.5, ~> 2.2, which is incompatible with the current version, ruby 3.0.2p107
```

Sorry, I'm not very experienced with ruby. Could you please advise what I may be doing wrong?

Thanks!

**Comment by mirthquake** [comment]
Never mind. Just removing the jekyll version dependency in Gemfile and deleting and recreating the Gemfile.lock appears to have solved this problem. Cheers!
